server:
  port: 8080
spring:
  application:
    name: portfolio-backend

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

  endpoint:
    health:
      show-details: always